//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBoutique.BoutiqueRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorie", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class Categorie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeCategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeCategorie {
            get {
                return this.CodeCategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeCategorieField, value) != true)) {
                    this.CodeCategorieField = value;
                    this.RaisePropertyChanged("CodeCategorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denomination {
            get {
                return this.DenominationField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominationField, value) != true)) {
                    this.DenominationField = value;
                    this.RaisePropertyChanged("Denomination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produit", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class Produit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUniteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrixUnitaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteMinimaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteQritiqueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeProduit {
            get {
                return this.CodeProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeProduitField, value) != true)) {
                    this.CodeProduitField = value;
                    this.RaisePropertyChanged("CodeProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignationProduit {
            get {
                return this.DesignationProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationProduitField, value) != true)) {
                    this.DesignationProduitField = value;
                    this.RaisePropertyChanged("DesignationProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategorie {
            get {
                return this.IdCategorieField;
            }
            set {
                if ((this.IdCategorieField.Equals(value) != true)) {
                    this.IdCategorieField = value;
                    this.RaisePropertyChanged("IdCategorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUnite {
            get {
                return this.IdUniteField;
            }
            set {
                if ((this.IdUniteField.Equals(value) != true)) {
                    this.IdUniteField = value;
                    this.RaisePropertyChanged("IdUnite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrixUnitaire {
            get {
                return this.PrixUnitaireField;
            }
            set {
                if ((this.PrixUnitaireField.Equals(value) != true)) {
                    this.PrixUnitaireField = value;
                    this.RaisePropertyChanged("PrixUnitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantiteMinimale {
            get {
                return this.QuantiteMinimaleField;
            }
            set {
                if ((this.QuantiteMinimaleField.Equals(value) != true)) {
                    this.QuantiteMinimaleField = value;
                    this.RaisePropertyChanged("QuantiteMinimale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantiteQritique {
            get {
                return this.QuantiteQritiqueField;
            }
            set {
                if ((this.QuantiteQritiqueField.Equals(value) != true)) {
                    this.QuantiteQritiqueField = value;
                    this.RaisePropertyChanged("QuantiteQritique");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProduitViewModel", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class ProduitViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantiteMinimaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantiteQritiqueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeProduit {
            get {
                return this.CodeProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeProduitField, value) != true)) {
                    this.CodeProduitField = value;
                    this.RaisePropertyChanged("CodeProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignationProduit {
            get {
                return this.DesignationProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationProduitField, value) != true)) {
                    this.DesignationProduitField = value;
                    this.RaisePropertyChanged("DesignationProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pu {
            get {
                return this.PuField;
            }
            set {
                if ((this.PuField.Equals(value) != true)) {
                    this.PuField = value;
                    this.RaisePropertyChanged("Pu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuantiteMinimale {
            get {
                return this.QuantiteMinimaleField;
            }
            set {
                if ((this.QuantiteMinimaleField.Equals(value) != true)) {
                    this.QuantiteMinimaleField = value;
                    this.RaisePropertyChanged("QuantiteMinimale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuantiteQritique {
            get {
                return this.QuantiteQritiqueField;
            }
            set {
                if ((this.QuantiteQritiqueField.Equals(value) != true)) {
                    this.QuantiteQritiqueField = value;
                    this.RaisePropertyChanged("QuantiteQritique");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockViewModel", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class StockViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrixUnitaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrixUnitaire {
            get {
                return this.PrixUnitaireField;
            }
            set {
                if ((this.PrixUnitaireField.Equals(value) != true)) {
                    this.PrixUnitaireField = value;
                    this.RaisePropertyChanged("PrixUnitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrixUnitaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduit {
            get {
                return this.IdProduitField;
            }
            set {
                if ((this.IdProduitField.Equals(value) != true)) {
                    this.IdProduitField = value;
                    this.RaisePropertyChanged("IdProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrixUnitaire {
            get {
                return this.PrixUnitaireField;
            }
            set {
                if ((this.PrixUnitaireField.Equals(value) != true)) {
                    this.PrixUnitaireField = value;
                    this.RaisePropertyChanged("PrixUnitaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unite", Namespace="http://schemas.datacontract.org/2004/07/BoutiqueWin.Model")]
    [System.SerializableAttribute()]
    public partial class Unite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string libelleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string libelle {
            get {
                return this.libelleField;
            }
            set {
                if ((object.ReferenceEquals(this.libelleField, value) != true)) {
                    this.libelleField = value;
                    this.RaisePropertyChanged("libelle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoutiqueRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClientBoutique.BoutiqueRef.CompositeType GetDataUsingDataContract(ClientBoutique.BoutiqueRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.CompositeType> GetDataUsingDataContractAsync(ClientBoutique.BoutiqueRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        ClientBoutique.BoutiqueRef.Categorie[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategories", ReplyAction="http://tempuri.org/IService1/GetCategoriesResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilteredCategories", ReplyAction="http://tempuri.org/IService1/GetFilteredCategoriesResponse")]
        ClientBoutique.BoutiqueRef.Categorie[] GetFilteredCategories(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilteredCategories", ReplyAction="http://tempuri.org/IService1/GetFilteredCategoriesResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie[]> GetFilteredCategoriesAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategorieById", ReplyAction="http://tempuri.org/IService1/GetCategorieByIdResponse")]
        ClientBoutique.BoutiqueRef.Categorie GetCategorieById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategorieById", ReplyAction="http://tempuri.org/IService1/GetCategorieByIdResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie> GetCategorieByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduitById", ReplyAction="http://tempuri.org/IService1/GetProduitByIdResponse")]
        ClientBoutique.BoutiqueRef.Produit GetProduitById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduitById", ReplyAction="http://tempuri.org/IService1/GetProduitByIdResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Produit> GetProduitByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduits", ReplyAction="http://tempuri.org/IService1/GetProduitsResponse")]
        ClientBoutique.BoutiqueRef.ProduitViewModel[] GetProduits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProduits", ReplyAction="http://tempuri.org/IService1/GetProduitsResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.ProduitViewModel[]> GetProduitsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntrees", ReplyAction="http://tempuri.org/IService1/GetEntreesResponse")]
        ClientBoutique.BoutiqueRef.StockViewModel[] GetEntrees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntrees", ReplyAction="http://tempuri.org/IService1/GetEntreesResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.StockViewModel[]> GetEntreesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSorties", ReplyAction="http://tempuri.org/IService1/GetSortiesResponse")]
        ClientBoutique.BoutiqueRef.StockViewModel[] GetSorties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSorties", ReplyAction="http://tempuri.org/IService1/GetSortiesResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.StockViewModel[]> GetSortiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategorie", ReplyAction="http://tempuri.org/IService1/AddCategorieResponse")]
        bool AddCategorie(ClientBoutique.BoutiqueRef.Categorie categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategorie", ReplyAction="http://tempuri.org/IService1/AddCategorieResponse")]
        System.Threading.Tasks.Task<bool> AddCategorieAsync(ClientBoutique.BoutiqueRef.Categorie categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduit", ReplyAction="http://tempuri.org/IService1/AddProduitResponse")]
        bool AddProduit(ClientBoutique.BoutiqueRef.Produit produit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduit", ReplyAction="http://tempuri.org/IService1/AddProduitResponse")]
        System.Threading.Tasks.Task<bool> AddProduitAsync(ClientBoutique.BoutiqueRef.Produit produit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStock", ReplyAction="http://tempuri.org/IService1/AddStockResponse")]
        bool AddStock(ClientBoutique.BoutiqueRef.Stock stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStock", ReplyAction="http://tempuri.org/IService1/AddStockResponse")]
        System.Threading.Tasks.Task<bool> AddStockAsync(ClientBoutique.BoutiqueRef.Stock stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategorie", ReplyAction="http://tempuri.org/IService1/UpdateCategorieResponse")]
        bool UpdateCategorie(ClientBoutique.BoutiqueRef.Categorie categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategorie", ReplyAction="http://tempuri.org/IService1/UpdateCategorieResponse")]
        System.Threading.Tasks.Task<bool> UpdateCategorieAsync(ClientBoutique.BoutiqueRef.Categorie categorie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduit", ReplyAction="http://tempuri.org/IService1/UpdateProduitResponse")]
        bool UpdateProduit(ClientBoutique.BoutiqueRef.Produit produit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduit", ReplyAction="http://tempuri.org/IService1/UpdateProduitResponse")]
        System.Threading.Tasks.Task<bool> UpdateProduitAsync(ClientBoutique.BoutiqueRef.Produit produit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStock", ReplyAction="http://tempuri.org/IService1/UpdateStockResponse")]
        bool UpdateStock(ClientBoutique.BoutiqueRef.Stock stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStock", ReplyAction="http://tempuri.org/IService1/UpdateStockResponse")]
        System.Threading.Tasks.Task<bool> UpdateStockAsync(ClientBoutique.BoutiqueRef.Stock stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategorie", ReplyAction="http://tempuri.org/IService1/DeleteCategorieResponse")]
        bool DeleteCategorie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategorie", ReplyAction="http://tempuri.org/IService1/DeleteCategorieResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategorieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduit", ReplyAction="http://tempuri.org/IService1/DeleteProduitResponse")]
        bool DeleteProduit(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduit", ReplyAction="http://tempuri.org/IService1/DeleteProduitResponse")]
        System.Threading.Tasks.Task<bool> DeleteProduitAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStock", ReplyAction="http://tempuri.org/IService1/DeleteStockResponse")]
        bool DeleteStock(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStock", ReplyAction="http://tempuri.org/IService1/DeleteStockResponse")]
        System.Threading.Tasks.Task<bool> DeleteStockAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WriteCsv", ReplyAction="http://tempuri.org/IService1/WriteCsvResponse")]
        bool WriteCsv(ClientBoutique.BoutiqueRef.Categorie[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WriteCsv", ReplyAction="http://tempuri.org/IService1/WriteCsvResponse")]
        System.Threading.Tasks.Task<bool> WriteCsvAsync(ClientBoutique.BoutiqueRef.Categorie[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnites", ReplyAction="http://tempuri.org/IService1/GetUnitesResponse")]
        ClientBoutique.BoutiqueRef.Unite[] GetUnites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUnites", ReplyAction="http://tempuri.org/IService1/GetUnitesResponse")]
        System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Unite[]> GetUnitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockGenerator", ReplyAction="http://tempuri.org/IService1/StockGeneratorResponse")]
        string StockGenerator();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StockGenerator", ReplyAction="http://tempuri.org/IService1/StockGeneratorResponse")]
        System.Threading.Tasks.Task<string> StockGeneratorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportXls", ReplyAction="http://tempuri.org/IService1/ExportXlsResponse")]
        bool ExportXls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportXls", ReplyAction="http://tempuri.org/IService1/ExportXlsResponse")]
        System.Threading.Tasks.Task<bool> ExportXlsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientBoutique.BoutiqueRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientBoutique.BoutiqueRef.IService1>, ClientBoutique.BoutiqueRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClientBoutique.BoutiqueRef.CompositeType GetDataUsingDataContract(ClientBoutique.BoutiqueRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.CompositeType> GetDataUsingDataContractAsync(ClientBoutique.BoutiqueRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ClientBoutique.BoutiqueRef.Categorie[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public ClientBoutique.BoutiqueRef.Categorie[] GetFilteredCategories(string search) {
            return base.Channel.GetFilteredCategories(search);
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie[]> GetFilteredCategoriesAsync(string search) {
            return base.Channel.GetFilteredCategoriesAsync(search);
        }
        
        public ClientBoutique.BoutiqueRef.Categorie GetCategorieById(int id) {
            return base.Channel.GetCategorieById(id);
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Categorie> GetCategorieByIdAsync(int id) {
            return base.Channel.GetCategorieByIdAsync(id);
        }
        
        public ClientBoutique.BoutiqueRef.Produit GetProduitById(int id) {
            return base.Channel.GetProduitById(id);
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Produit> GetProduitByIdAsync(int id) {
            return base.Channel.GetProduitByIdAsync(id);
        }
        
        public ClientBoutique.BoutiqueRef.ProduitViewModel[] GetProduits() {
            return base.Channel.GetProduits();
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.ProduitViewModel[]> GetProduitsAsync() {
            return base.Channel.GetProduitsAsync();
        }
        
        public ClientBoutique.BoutiqueRef.StockViewModel[] GetEntrees() {
            return base.Channel.GetEntrees();
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.StockViewModel[]> GetEntreesAsync() {
            return base.Channel.GetEntreesAsync();
        }
        
        public ClientBoutique.BoutiqueRef.StockViewModel[] GetSorties() {
            return base.Channel.GetSorties();
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.StockViewModel[]> GetSortiesAsync() {
            return base.Channel.GetSortiesAsync();
        }
        
        public bool AddCategorie(ClientBoutique.BoutiqueRef.Categorie categorie) {
            return base.Channel.AddCategorie(categorie);
        }
        
        public System.Threading.Tasks.Task<bool> AddCategorieAsync(ClientBoutique.BoutiqueRef.Categorie categorie) {
            return base.Channel.AddCategorieAsync(categorie);
        }
        
        public bool AddProduit(ClientBoutique.BoutiqueRef.Produit produit) {
            return base.Channel.AddProduit(produit);
        }
        
        public System.Threading.Tasks.Task<bool> AddProduitAsync(ClientBoutique.BoutiqueRef.Produit produit) {
            return base.Channel.AddProduitAsync(produit);
        }
        
        public bool AddStock(ClientBoutique.BoutiqueRef.Stock stock) {
            return base.Channel.AddStock(stock);
        }
        
        public System.Threading.Tasks.Task<bool> AddStockAsync(ClientBoutique.BoutiqueRef.Stock stock) {
            return base.Channel.AddStockAsync(stock);
        }
        
        public bool UpdateCategorie(ClientBoutique.BoutiqueRef.Categorie categorie) {
            return base.Channel.UpdateCategorie(categorie);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCategorieAsync(ClientBoutique.BoutiqueRef.Categorie categorie) {
            return base.Channel.UpdateCategorieAsync(categorie);
        }
        
        public bool UpdateProduit(ClientBoutique.BoutiqueRef.Produit produit) {
            return base.Channel.UpdateProduit(produit);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProduitAsync(ClientBoutique.BoutiqueRef.Produit produit) {
            return base.Channel.UpdateProduitAsync(produit);
        }
        
        public bool UpdateStock(ClientBoutique.BoutiqueRef.Stock stock) {
            return base.Channel.UpdateStock(stock);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStockAsync(ClientBoutique.BoutiqueRef.Stock stock) {
            return base.Channel.UpdateStockAsync(stock);
        }
        
        public bool DeleteCategorie(int id) {
            return base.Channel.DeleteCategorie(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategorieAsync(int id) {
            return base.Channel.DeleteCategorieAsync(id);
        }
        
        public bool DeleteProduit(int id) {
            return base.Channel.DeleteProduit(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProduitAsync(int id) {
            return base.Channel.DeleteProduitAsync(id);
        }
        
        public bool DeleteStock(int id) {
            return base.Channel.DeleteStock(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStockAsync(int id) {
            return base.Channel.DeleteStockAsync(id);
        }
        
        public bool WriteCsv(ClientBoutique.BoutiqueRef.Categorie[] list) {
            return base.Channel.WriteCsv(list);
        }
        
        public System.Threading.Tasks.Task<bool> WriteCsvAsync(ClientBoutique.BoutiqueRef.Categorie[] list) {
            return base.Channel.WriteCsvAsync(list);
        }
        
        public ClientBoutique.BoutiqueRef.Unite[] GetUnites() {
            return base.Channel.GetUnites();
        }
        
        public System.Threading.Tasks.Task<ClientBoutique.BoutiqueRef.Unite[]> GetUnitesAsync() {
            return base.Channel.GetUnitesAsync();
        }
        
        public string StockGenerator() {
            return base.Channel.StockGenerator();
        }
        
        public System.Threading.Tasks.Task<string> StockGeneratorAsync() {
            return base.Channel.StockGeneratorAsync();
        }
        
        public bool ExportXls() {
            return base.Channel.ExportXls();
        }
        
        public System.Threading.Tasks.Task<bool> ExportXlsAsync() {
            return base.Channel.ExportXlsAsync();
        }
    }
}
